name: Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ArtemSashkin/buildozer-action@v1
        with:
          command: android debug
      - uses: actions/upload-artifact@v2
        with:
          name: Nova-App
          path: bin/*.apk